### ISSUE TITLE
[FALSE-POSITIVE] mi.edgekey.net 

### ISSUE THREAD

**Issue by p1r473** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#592]
**Describe the subjects (domains)**
mi.edgekey.net 

**More Information**
Tried to visit miamiherald.com which happens above domain is CNAME for.

1. Can't visit.
2. Spontaneous lookup.
3. ...

**Have you requested removal from other sources?**

https://github.com/d43m0nhLInt3r/socialblocklists/issues/22

**WARNING:** Please [search in our infrastructure](https://hosts.ubuntu101.co.za/app/contents) before submitting it.
https://hosts.ubuntu101.co.za/app/contents is DOWN, giving error.
![image](https://user-images.githubusercontent.com/9235633/98167575-4a570f00-1eb7-11eb-8a59-d1e11a5bf16b.png)

**Additional context**
mi.edgekey.net is a false positive

edgekey.net is a domain that is owned and used by Akamai that is primarily used for website acceleration through the Akamai CDN. Content Delivery Networks (CDNs) put website content on servers that are spread throughout the world.

its also a CNAME for several sites such as miamiherald.com.

**Comment by dnmTX** [comment]
@p1r473 we need to find out from which list this coming from first. I have this domain blocked on my end as well and i checked all of the original lists that i'm using and none showed up but the thing is that i'm loading those lists from here and most of them didn't get updated/filtered properly for a long time so i'll assume  that the domain in question was removed from the upstream but due to problems with the filtering here it's still present. So this will be pending issue for now.
@funilrys move it to us please when you have time. Thanks 👍

**Comment by funilrys** [comment]
@dnmTX You should be able to move it yourself now that this repository is in our organization 😉  Can you try it ?

`/move to Ultimate-Hosts-Blacklist/whitelist` as comment (alone with anything else)

**Comment by dnmTX** [comment]
@funilrys worked 👍  Thanks for the help, it will be much easier now to deal with false-positives.
