### ISSUE TITLE
[FEATURE] Searching and adding ipv6 ip of the bad ip list.

### ISSUE THREAD

**Issue by BirdInFire** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#601]
**Is your feature request related to a problem? Please describe.**
If i understand the ip list bad guy only use ipv4 for their bad thing.

**Describe the solution you'd like**
Having a list of bad ipv6 actor and not ipv4 only.

**Comment by michaelb-ae** [comment]
i know it's not easy, so at your place i label it at low issue, but it's an issues for those who have double stack (ipv4 and 6) because bad guy can connect through ipv6 and just blocking ipv6 solve the problem rapidly but when all people will be forced to migrate to ipv6 all our protection will fall

**Comment by Somebodyisnobody** [comment]
As I know on windows systems there should be no lookup to an dns resolver when there's an entry in the hosts file.

**Comment by michaelb-ae** [comment]
i was actually talking about the list of ip who is more conceived for firewall or DNS server, if a dns server (pihole or thing like that) add the ip list, the user resolve the domaine ipv4 will fail but it will success on V6.
but I agree that this has no interest in the case of host, in my own case i protect all my device in one go on dns level since some device don't let us modify host (android, ios, os from tv, etc..).
