### ISSUE TITLE
[FALSE-POSITIVE] impots.gouv.fr

### ISSUE THREAD

**Issue by nodje** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#636]

**Comment by nodje** [comment]
Hey,

I'm pretty sure I already reported this, French tax official website, but I can't find the closed issue here for some reason.

Anyway, here' s list of French IRS related domains, + some others i stumbled upon.

impots.gouv.fr
www3.impots.gouv.fr
cfspart.impots.gouv.fr
www.impots.gouv.fr
idp.impots.gouv.fr

(clearly, *.impots.gouv.fr should never be blacklisted)

In addition:
mandrillapp.com
www.newsletter.institutmontaigne.org

**Comment by nodje** [comment]
Sorry about misnaming the issue. Would be nice to have this processed.
cheers

**Comment by dnmTX** [comment]
@nodje sorry about the delay and this is what i see so far:
`impots.gouv.fr` has been removed from upstream(by your request,see https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues/180) and it's not present here. Try to update your list.
The rest of `*.impots.gouv.fr` mentioned in your post above are not present here either.
**ping** Mitch @mitchellkrogza  to assist with `mandrillapp.com`
Regarding `go.pardot.com`. It's a known tracker and it will stay. I see that whatever you're using on your end blocks CNAME's as well so i would suggest to whitelist it.
In addition,due to many of the lists here are not properly updating with upstream and filtering as well for a long time and it looks like the main developer of this project lost interest maintaing it,i would highly advise you to look for a different blocklist,which is better maintained and updated 👍

**Comment by nodje** [comment]
roger this, thanks
