### ISSUE TITLE
hosts.ubuntu101.co.za - certificate expired

### ISSUE THREAD

**Issue by tonhogen** [Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#661]
Hi,

just in case you are not aware of the certication expiration:  my (weekly) pihole update of your (excellent!) blocklist failed with error 'access denied'. I think this is happening because the  Let's Encrypt certificate for hosts.ubuntu101.co.za  expired on dec 9th and no https connections are allowed.

**Comment by funilrys** [comment]
Hello everyone, thank you for reporting. The issue was fixed in the morning (Berlin Time).

For those wondering how could that happen:

We use certbot to automatically renew our certificates, but while trying to update the DNS TXT record, the DNS server refused to accept the changes because of a time difference. It turned out that the server was out of sync - a few hours back. 
After fixing the time issue, certbot could automatically renew all our certificates. 

Sorry for the waiting time. 

For the next one who reads this: Don't be afraid to \@\mention me or send me an email. 
Stay safe and healthy.
